######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 12 02:14:45 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += copier.h
SOURCES += copier.cpp main.cpp
